commandname: RepoUpdateCommand
commandargs:
  RepoID: 1
subnode:
  success:
    commandname: RepoArchiveCommand
    commandargs:
      RepoID: 1
      Format: tar
      Branch: master
      OutFile: a.tar
    subnode:
      success:
        commandname: DockerBuildArchiveCommand
        commandargs:
          DockerID: 1
          File: a.tar
          Name: captain
